# logging settings
logging:
  level:
    root: info
    de:
      flapdoodle: warn
    org:
      apache: warn
      mongodb: warn
      springframework:
        boot: warn
        web: trace
    reactor: error

  pattern:
    console: '%clr([%date{HH:mm:ss}]){faint} %clr(%thread) %clr(%2p) %clr(%-30.30logger{36}){cyan} %m%n%wex'

spring:
  jackson:
    serialization:
      indent_output: true
    default-property-inclusion: non_null
