# logging settings
logging:
  level:
    root: info
    io: warn
    org:
      apache: warn
      springframework: warn
    reactor: error

  pattern:
    console: '%clr([%date{HH:mm:ss}]){faint} %clr(%2p) %clr(%-30.30logger{36}){cyan} %m%n%wex'