spring:
  application:
    name: 'rsocket-interaction-models'

  jackson:
    serialization:
      indent_output: true
    default-property-inclusion: non_null

  rsocket:
    server:
      port: 9899
      transport: tcp

logging:
  level:
    root: info
    ca:
      uhn: warn
    org:
      apache: warn
      springframework: warn
  pattern:
    console: '%clr([%date{HH:mm:ss.SSS}]){faint} %clr(%2p) %clr(%-40.40logger{36}){cyan} %m%n%wex'