# logging settings
logging:
  level:
    root: info
    org:
      apache: warn
      mongodb: warn
      springframework: warn
    reactor: error

  pattern:
    console: '%clr([%date{HH:mm:ss.SSS}]){faint} %clr(%2p) %clr(%-30.30logger{36}){cyan} %m%n%wex'

spring:
  jackson:
    serialization:
      indent_output: true
    default-property-inclusion: non_null

  cloud:
    stream:
      bindings:
        input:
          destination: orders
          #group: orders-group
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8081
